added autoloading
arkadiusjonczek/laravel-command-dbcreate pull request #1
Opened 2019-07-05 18:10 UTC by mrvnklm

2019-09-10 22:03 UTC, arkadiusjonczek requested changes
Hey @mrvnklm , thank you for your PR. 👍 
I reviewed it and added some comments to review for you. Please take a look at it. :)

2019-09-10 22:03 UTC, arkadiusjonczek commented on composer.json
> +            "Arkadiusjonczek\\DbCreateCommand\\": "src/"
Why did you change the namespace? I did this on purpose and it worked very well. ;)

2019-09-10 22:03 UTC, arkadiusjonczek commented on composer.json
> +                "Arkadiusjonczek\\DbCreateCommand\\DbCreateServiceProvider"
I like the idea with the laravel service provider! 👍 🥇

2019-09-10 22:03 UTC, arkadiusjonczek commented on src/DbCreateCommand.php
> +class DbCreateCommand extends Command
There is no need to use "Command" as postfix. See https://laravel.com/docs/5.8/artisan#command-structure

2019-09-24 09:31 UTC, mrvnklm commented on composer.json
> +            "Arkadiusjonczek\\DbCreateCommand\\": "src/"
Actually I am wondering, why I did that - sorry

2019-09-24 09:32 UTC, mrvnklm commented on src/DbCreateCommand.php
> +class DbCreateCommand extends Command
True, coming from Symfony made me do this O:-)

2019-09-24 10:35 UTC, arkadiusjonczek commented on src/DbCreateCommand.php
> +class DbCreateCommand extends Command
I'm fine with this. ;)

2019-09-24 10:36 UTC, arkadiusjonczek commented on composer.json
> +            "Arkadiusjonczek\\DbCreateCommand\\": "src/"
Please undo this so I can merge this PR. ;) @mrvnklm

2019-09-24 10:37 UTC, arkadiusjonczek requested changes
See my latest comments. ;) @mrvnklm

2019-10-09 09:57 UTC, mrvnklm commented
> See my latest comments. ;) @mrvnklm 

I reverted the composer.json

2019-10-10 12:50 UTC, arkadiusjonczek commented
Hey @mrvnklm , please update all other namespace to `App\Console\`, too. ;)

2019-11-17 00:00 UTC, arkadiusjonczek commented
I added the changes with commit 7ba4d214fddd9a03faab227fe1addd84fa1f11c4

2019-11-17 00:00 UTC, closed without merging